baseURL = '/'
uglyURLs = true
relativeURLs = true
languageCode = 'pl'
title = 'Deans Paranois Documentation'
# Change the default theme
theme = "hugo-theme-relearn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
